import { LiveChannel } from '../types';


export const LIVE_CHANNELS: LiveChannel[] = [
  { name: 'HBO (USA)', embed: 'https://dlhd.dad/stream/stream-321.php', category: 'Premium Movies', channelNumber: 100, image: 'https://upload.wikimedia.org/wikipedia/commons/d/de/HBO_logo.svg' },
  { name: 'Cartoon Network', embed: 'https://dlhd.dad/stream/stream-339.php', category: 'Kids', channelNumber: 1, image: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Cartoon_Network_2010_logo.svg' },
  { name: 'NICK', embed: 'https://dlhd.dad/stream/stream-330.php', category: 'Kids', channelNumber: 2, image: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Nickelodeon_logo.svg' },
  { name: 'Nicktoons', embed: 'https://dlhd.dad/stream/stream-649.php', category: 'Kids', channelNumber: 3 },
  { name: 'Disney Channel', embed: 'https://dlhd.dad/stream/stream-312.php', category: 'Kids', channelNumber: 4, image: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Disney_Channel_logo_2014.svg' },
  { name: 'Disney XD', embed: 'https://dlhd.dad/stream/stream-314.php', category: 'Kids', channelNumber: 5, image: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Disney_XD_logo.svg' },
  { name: 'Disney JR', embed: 'https://dlhd.dad/stream/stream-652.php', category: 'Kids', channelNumber: 6, image: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Disney_Junior_2020.svg' },
  { name: 'Nick JR', embed: 'https://dlhd.dad/stream/stream-329.php', category: 'Kids', channelNumber: 7, image: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Nick_Jr._2023.svg' },
  { name: 'Sky Sports Premier League', embed: 'https://dlhd.dad/stream/stream-130.php', category: 'Sports', channelNumber: 8 },
  { name: 'Fox Sports 1', embed: 'https://dlhd.dad/stream/stream-39.php', category: 'Sports', channelNumber: 9 },
  { name: 'Fox Sports 2', embed: 'https://dlhd.dad/stream/stream-758.php', category: 'Sports', channelNumber: 10 },
  { name: 'ESPN USA', embed: 'https://dlhd.dad/stream/stream-44.php', category: 'Sports', channelNumber: 11, image: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/ESPN_logo.svg' },
  { name: 'NHL', embed: 'https://dlhd.dad/stream/stream-663.php', category: 'Sports', channelNumber: 12, image: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/NHL_Logo.svg' },
  { name: 'NFL', embed: 'https://dlhd.dad/stream/stream-405.php', category: 'Sports', channelNumber: 13, image: 'https://upload.wikimedia.org/wikipedia/en/a/a2/National_Football_League_logo.svg' },
  { name: 'NBA', embed: 'https://dlhd.dad/stream/stream-404.php', category: 'Sports', channelNumber: 14, image: 'https://upload.wikimedia.org/wikipedia/en/0/03/National_Basketball_Association_logo.svg' },
  { name: 'beIN Sports', embed: 'https://dlhd.dad/stream/stream-425.php', category: 'Sports', channelNumber: 15, image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/BeIN_Sports_English_logo.svg/512px-BeIN_Sports_English_logo.svg.png' },
  { name: 'Sky Sports Cricket', embed: 'https://dlhd.dad/stream/stream-65.php', category: 'Sports', channelNumber: 16 },
  { name: 'WWE', embed: 'https://dlhd.dad/stream/stream-376.php', category: 'Sports', channelNumber: 17, image: 'https://upload.wikimedia.org/wikipedia/commons/0/03/WWE_Logo.svg' },
  { name: 'NBC USA', embed: 'https://dlhd.dad/stream/stream-53.php', category: 'Entertainment', channelNumber: 18, image: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/NBC_logo.svg' },
  { name: 'FX USA', embed: 'https://dlhd.dad/stream/stream-317.php', category: 'Entertainment', channelNumber: 19 },
  { name: 'Animal Planet', embed: 'https://dlhd.dad/stream/stream-304.php', category: 'Documentary', channelNumber: 20, image: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Animal_Planet_2018.svg' },
  { name: 'Fox News', embed: 'https://dlhd.dad/stream/stream-347.php', category: 'News', channelNumber: 21, image: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Fox_News_Channel_logo.svg' },
  { name: 'CNN', embed: 'https://dlhd.dad/stream/stream-345.php', category: 'News', channelNumber: 22, image: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/CNN.svg' },
  { name: 'ABC USA', embed: 'https://dlhd.dad/stream/stream-51.php', category: 'News', channelNumber: 23, image: 'https://upload.wikimedia.org/wikipedia/commons/4/43/ABC_logo_2021.svg' },
  { name: 'MSNBC', embed: 'https://dlhd.dad/stream/stream-327.php', category: 'News', channelNumber: 24 },
  { name: 'CNBC', embed: 'https://dlhd.dad/stream/stream-309.php', category: 'News', channelNumber: 25 },
  { name: 'History USA', embed: 'https://dlhd.dad/stream/stream-322.php', category: 'Documentary', channelNumber: 26 },
  { name: 'Univision', embed: 'https://dlhd.dad/stream/stream-132.php', category: 'Entertainment', channelNumber: 27 },
  { name: 'HGTV', embed: 'https://dlhd.dad/stream/stream-382.php', category: 'Lifestyle', channelNumber: 28 },
  { name: 'USA Network', embed: 'https://dlhd.dad/stream/stream-343.php', category: 'Entertainment', channelNumber: 29 },
  { name: 'TLC', embed: 'https://dlhd.dad/stream/stream-337.php', category: 'Lifestyle', channelNumber: 30 },
  { name: 'TBS', embed: 'https://dlhd.dad/stream/stream-336.php', category: 'Entertainment', channelNumber: 31 },
  { name: 'CBS', embed: 'https://dlhd.dad/stream/stream-52.php', category: 'Entertainment', channelNumber: 32 },
  { name: 'Telemundo', embed: 'https://dlhd.dad/stream/stream-52.php', category: 'Entertainment', channelNumber: 33 },
  { name: 'Boomerang', embed: 'https://dlhd.dad/stream/stream-648.php', category: 'Kids', channelNumber: 34 },
  
  { name: 'Telemundo', embed: 'https://dlhd.dad/stream/stream-52.php', category: 'Entertainment', channelNumber: 33 },
  { name: 'Boomerang', embed: 'https://dlhd.dad/stream/stream-648.php', category: 'Kids', channelNumber: 34 },
  
  // Argentina channels (Full List)
  { "name": "5TV Corrientes (480p) [Not 24/7]", "embed": "hls-player.html?url=http://www.coninfo.net:1935/tvcinco/live1/playlist.m3u8", "category": "Argentina", "channelNumber": 200 },
  { "name": "24/7 Canal de Noticias", "embed": "hls-player.html?url=https://panel.host-live.com:19360/cn247tv/cn247tv.m3u8", "category": "Argentina", "channelNumber": 201 },
  { "name": "A24 (720p)", "embed": "hls-player.html?url=https://g5.vxral-slo.transport.edge-access.net/a12/ngrp:a24-100056_all/playlist.m3u8?sense=true", "category": "Argentina", "channelNumber": 202 },
  { "name": "Aire de Santa Fe (1080p)", "embed": "hls-player.html?url=https://unlimited1-us.dps.live/airedesantafetv/airedesantafetv.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 203 },
  { "name": "Alterna TV (720p) [Not 24/7]", "embed": "hls-player.html?url=https://tv.alterna.ar/stream/hls/live.m3u8", "category": "Argentina", "channelNumber": 204 },
  { "name": "America TV (720p)", "embed": "hls-player.html?url=https://prepublish.f.qaotic.net/a07/americahls-100056/playlist_720p.m3u8", "category": "Argentina", "channelNumber": 205 },
  { "name": "Argentinísima Satelital (540p)", "embed": "hls-player.html?url=https://stream1.sersat.com/hls/argentinisima.m3u8", "category": "Argentina", "channelNumber": 206 },
  { "name": "ATV Argentina", "embed": "hls-player.html?url=https://tv.streaming.com.bo/atvargentina/index.m3u8", "category": "Argentina", "channelNumber": 207 },
  { "name": "Azahares Radio Multimedia (720p)", "embed": "hls-player.html?url=https://streamyes.alsolnet.com/azaharesfm/live/playlist.m3u8", "category": "Argentina", "channelNumber": 208 },
  { "name": "Bayres TV (720p)", "embed": "hls-player.html?url=https://streaming01.mikrolive.tv/bayrestv/live/playlist.m3u8", "category": "Argentina", "channelNumber": 209 },
  { "name": "Beats Radio (480p)", "embed": "hls-player.html?url=https://videostream.shockmedia.com.ar:19360/beatsradio/beatsradio.m3u8", "category": "Argentina", "channelNumber": 210 },
  { "name": "Bravo TV", "embed": "hls-player.html?url=https://redirector.rudo.video/hls-video/c54ac2799874375c81c1672abb700870537c5223/bravo/bravo.smil/playlist.m3u8?did=b2201035844768f58630b7eef", "category": "Argentina", "channelNumber": 211 },
  { "name": "Cable Imagen Armstrong (540p) [Not 24/7]", "embed": "hls-player.html?url=https://stream.arcast.com.ar/casse/casse/playlist.m3u8", "category": "Argentina", "channelNumber": 212 },
  { "name": "Cadena 103 (720p) [Not 24/7]", "embed": "hls-player.html?url=http://arcast.net:1935/cadena103/cadena103/playlist.m3u8", "category": "Argentina", "channelNumber": 213 },
  { "name": "Canal 2 de Ushuaia (1080p)", "embed": "hls-player.html?url=https://nd106.republicaservers.com:4433/hls/c6611/index.m3u8", "category": "Argentina", "channelNumber": 214 },
  { "name": "Canal 2 Misiones (1080p)", "embed": "hls-player.html?url=https://nd106.republicaservers.com:4433/hls/canal2misioness/index.m3u8", "category": "Argentina", "channelNumber": 215 },
  { "name": "Canal 3 La Pampa (1080p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/c3lapampa/ngrp:c3lapampa_all/playlist.m3u8", "category": "Argentina", "channelNumber": 216 },
  { "name": "Canal 3 Las Heras (720p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/canal3/canal3/playlist.m3u8", "category": "Argentina", "channelNumber": 217 },
  { "name": "Canal 4 Jujuy", "embed": "hls-player.html?url=https://5cd577a3dd8ec.streamlock.net/CANAL4/smil:CANAL4.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 218 },
  { "name": "Canal 4 Posadas (576p)", "embed": "hls-player.html?url=https://iptv.ixfo.com.ar:30443/live/C4POS/playlist.m3u8", "category": "Argentina", "channelNumber": 219 },
  { "name": "Canal 4 San Juan (576p)", "embed": "hls-player.html?url=https://streamlov.alsolnet.com/canal4sanjuan/live/playlist.m3u8", "category": "Argentina", "channelNumber": 220 },
  { "name": "Canal 5 Del Pueblo [Not 24/7]", "embed": "hls-player.html?url=https://stmv4.voxtvhd.com.br/canal5pueblo/canal5pueblo/playlist.m3u8", "category": "Argentina", "channelNumber": 221 },
  { "name": "Canal 5 Santa Fe (240p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/c5sf/c5sf/playlist.m3u8", "category": "Argentina", "channelNumber": 222 },
  { "name": "Canal 5 TV Chepes", "embed": "hls-player.html?url=https://videostream.shockmedia.com.ar:19360/canal5alfatvchepes/canal5alfatvchepes.m3u8", "category": "Argentina", "channelNumber": 223 },
  { "name": "Canal 6 Posadas (1080p)", "embed": "hls-player.html?url=https://iptv.ixfo.com.ar:30443/live/c6digital/playlist.m3u8", "category": "Argentina", "channelNumber": 224 },
  { "name": "Canal 7 Jujuy", "embed": "hls-player.html?url=https://stream.arcast.live/canal7jujuy/ngrp:canal7jujuy_all/playlist.m3u8", "category": "Argentina", "channelNumber": 225 },
  { "name": "Canal 7 Neuquén (1080p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/c7nq/ngrp:c7nq_all/playlist.m3u8", "category": "Argentina", "channelNumber": 226 },
  { "name": "Canal 7 Salta (1080p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/cooperativa/cooperativa.m3u8", "category": "Argentina", "channelNumber": 227 },
  { "name": "Canal 7 Salta (720p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/canal7salta/canal7salta.m3u8", "category": "Argentina", "channelNumber": 228 },
  { "name": "Canal 7 Santiago del Estero (720p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/envivo/castv/playlist.m3u8", "category": "Argentina", "channelNumber": 229 },
  { "name": "Canal 9 Litoral (720p)", "embed": "hls-player.html?url=https://stream.arcast.live/ahora/ahora/playlist.m3u8", "category": "Argentina", "channelNumber": 230 },
  { "name": "Canal 9 Resistencia (720p)", "embed": "hls-player.html?url=http://coninfo.net:1935/9linklivert/smil:9linkmultibr.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 231 },
  { "name": "Canal 9 Televida", "embed": "hls-player.html?url=https://unlimited1-saopaulo.dps.live/televidaar/televidaar.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 232 },
  { "name": "Canal 10 Cordoba", "embed": "hls-player.html?url=https://stream.arcast.net:4443/canal10/ngrp:canal10_all/playlist.m3u8", "category": "Argentina", "channelNumber": 233 },
  { "name": "Canal 11 de la Costa (720p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/dadaproductora/dadaproductora.m3u8", "category": "Argentina", "channelNumber": 234 },
  { "name": "Canal 12 Puerto Madryn (720p) [Not 24/7]", "embed": "hls-player.html?url=https://5f700d5b2c46f.streamlock.net/madryntv/madryntv/playlist.m3u8", "category": "Argentina", "channelNumber": 235 },
  { "name": "Canal 13 Jujuy TV (720p)", "embed": "hls-player.html?url=https://genexservicios.com:19360/canal13jujuy/canal13jujuy.m3u8", "category": "Argentina", "channelNumber": 236 },
  { "name": "Canal 13 La Rioja (480p)", "embed": "hls-player.html?url=http://arcast.net:1935/mp/mp/playlist.m3u8", "category": "Argentina", "channelNumber": 237 },
  { "name": "Canal 13 San Luis", "embed": "hls-player.html?url=https://stream.radiosmundiales.com:19360/sanluismas/sanluismas.m3u8", "category": "Argentina", "channelNumber": 238 },
  { "name": "Canal 21 TV (1080p)", "embed": "hls-player.html?url=https://iptv.ixfo.com.ar:30443/c21tv/hd/c21tv/playlist.m3u8", "category": "Argentina", "channelNumber": 239 },
  { "name": "Canal 22 (720p)", "embed": "hls-player.html?url=https://5f700d5b2c46f.streamlock.net/canal22/canal22/playlist.m3u8", "category": "Argentina", "channelNumber": 240 },
  { "name": "Canal 26 (1080p)", "embed": "hls-player.html?url=https://stream-gtlc.telecentro.net.ar/hls/canal26hls/main.m3u8", "category": "Argentina", "channelNumber": 241 },
  { "name": "Canal 26", "embed": "hls-player.html?url=https://stream-gtlc.telecentro.net.ar/hls/canal26hls/0/playlist.m3u8", "category": "Argentina", "channelNumber": 242 },
  { "name": "Canal 34 San Juan (720p)", "embed": "hls-player.html?url=https://streamyes.alsolnet.com/canal34hd/live/playlist.m3u8", "category": "Argentina", "channelNumber": 243 },
  { "name": "Canal 79 La Costa (240p)", "embed": "hls-player.html?url=https://streamconex.com:19360/lacosta/lacosta.m3u8", "category": "Argentina", "channelNumber": 244 },
  { "name": "Canal 79 Mar del Plata", "embed": "hls-player.html?url=https://streamconex.com:19360/mardelplata/mardelplata.m3u8", "category": "Argentina", "channelNumber": 245 },
  { "name": "Canal 79 Puan (240p)", "embed": "hls-player.html?url=https://streamconex.com:19360/puan/puan.m3u8", "category": "Argentina", "channelNumber": 246 },
  { "name": "Canal 79 Santa Clara del Mar (240p)", "embed": "hls-player.html?url=https://streamconex.com:19360/santaclara-1/santaclara-1.m3u8", "category": "Argentina", "channelNumber": 247 },
  { "name": "Canal E (720p)", "embed": "hls-player.html?url=https://unlimited1-us.dps.live/perfiltv/perfiltv.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 248 },
  { "name": "Canal Orbe 21", "embed": "hls-player.html?url=https://stream.arcast.net:4443/canal21/ngrp:canal21_all/playlist.m3u8", "category": "Argentina", "channelNumber": 249 },
  { "name": "Canal Provincial (360p)", "embed": "hls-player.html?url=https://streaming.telered.com.ar/provincial/streaming/mystream.m3u8", "category": "Argentina", "channelNumber": 250 },
  { "name": "Canal Santa María (360p)", "embed": "hls-player.html?url=https://streaming.telered.com.ar/santa-maria/streaming/mystream.m3u8", "category": "Argentina", "channelNumber": 251 },
  { "name": "Catamarca TV (720p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/canal7catamarca/ngrp:canal7catamarca_all/playlist.m3u8?DVR=", "category": "Argentina", "channelNumber": 252 },
  { "name": "Celta TV (240p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/celta/celta.m3u8", "category": "Argentina", "channelNumber": 253 },
  { "name": "Chaco TV (720p) [Not 24/7]", "embed": "hls-player.html?url=https://wowzasrv.chaco.gov.ar/Streamtv/chacotv/playlist.m3u8", "category": "Argentina", "channelNumber": 254 },
  { "name": "Chilecito TV (480p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/grupoemail/grupoemail.m3u8", "category": "Argentina", "channelNumber": 255 },
  { "name": "Ciudad Magazine (1080p) [Geo-blocked]", "embed": "hls-player.html?url=https://live-01-07-ciudad.vodgc.net/live-01-07-ciudad.vodgc.net/index.m3u8", "category": "Argentina", "channelNumber": 256 },
  { "name": "Cumbia Mix (720p)", "embed": "hls-player.html?url=https://cloud.tvomix.com/CUMBIAMIX/index.m3u8", "category": "Argentina", "channelNumber": 257 },
  { "name": "Disney Channel Latin America (1080p)", "embed": "hls-player.html?url=http://201.230.121.186:8000/play/a0fb/index.m3u8", "category": "Argentina", "channelNumber": 258 },
  { "name": "El Trece (1080p)", "embed": "hls-player.html?url=https://live-01-02-eltrece.vodgc.net/eltrecetv/index.m3u8", "category": "Argentina", "channelNumber": 259 },
  { "name": "El Trece (1080p)", "embed": "hls-player.html?url=https://livetrx01.vodgc.net/eltrecetv/index.m3u8", "category": "Argentina", "channelNumber": 260 },
  { "name": "Garage TV Latin America", "embed": "hls-player.html?url=https://stream1.sersat.com/hls/garagetv.m3u8", "category": "Argentina", "channelNumber": 261 },
  { "name": "Kpop Mix (720p)", "embed": "hls-player.html?url=https://cloud.tvomix.com/KPOPMIX/index.m3u8", "category": "Argentina", "channelNumber": 262 },
  { "name": "Litus TV (720p)", "embed": "hls-player.html?url=https://stream.arcast.com.ar/litustv/ngrp:litustv_all/playlist.m3u8", "category": "Argentina", "channelNumber": 263 },
  { "name": "Magic Kids (486p)", "embed": "hls-player.html?url=https://magicstream.ddns.net/magicstream/stream.m3u8", "category": "Argentina", "channelNumber": 264 },
  { "name": "Más FM 95.9 (720p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/masfm/masfm.m3u8", "category": "Argentina", "channelNumber": 265 },
  { "name": "Metro TV (720p)", "embed": "hls-player.html?url=https://streamtv12.ddns.net:5443/LiveApp/streams/193945633734205616732920.m3u8", "category": "Argentina", "channelNumber": 266 },
  { "name": "Milennio TV (720p)", "embed": "hls-player.html?url=https://videostream.shockmedia.com.ar:19360/milenniotv/milenniotv.m3u8", "category": "Argentina", "channelNumber": 267 },
  { "name": "Misiones Cuatro", "embed": "hls-player.html?url=https://iptv.ixfo.com.ar:30443/live-HD/MISIONES4/playlist.m3u8", "category": "Argentina", "channelNumber": 268 },
  { "name": "Multivision Federal", "embed": "hls-player.html?url=https://panel.host-live.com:19360/8250/8250.m3u8", "category": "Argentina", "channelNumber": 269 },
  { "name": "NET TV (720p)", "embed": "hls-player.html?url=https://unlimited1-us.dps.live/nettv/nettv.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 270 },
  { "name": "NET TV (720p)", "embed": "hls-player.html?url=https://unlimited6-cl.dps.live/nettv/nettv.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 271 },
  { "name": "NG Federal (720p)", "embed": "hls-player.html?url=http://www.coninfo.net:1935/tvlink/live/playlist.m3u8", "category": "Argentina", "channelNumber": 272 },
  { "name": "Panc TV (720p) [Not 24/7]", "embed": "hls-player.html?url=https://panel.host-live.com:19360/20004/20004.m3u8", "category": "Argentina", "channelNumber": 273 },
  { "name": "Power Max Radio TV (720p)", "embed": "hls-player.html?url=https://videostream.shockmedia.com.ar:19360/radio1045/radio1045.m3u8", "category": "Argentina", "channelNumber": 274 },
  { "name": "Radio Conexion Web TV (720p)", "embed": "hls-player.html?url=https://tuvideoonline.com.ar:3391/live/radioconexionlive.m3u8", "category": "Argentina", "channelNumber": 275 },
  { "name": "Radio Realpolitik (720p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/realpolitik/realpolitik.m3u8", "category": "Argentina", "channelNumber": 276 },
  { "name": "Radio Sublime Gracia TV (720p)", "embed": "hls-player.html?url=https://5f700d5b2c46f.streamlock.net/sublime/sublime/playlist.m3u8", "category": "Argentina", "channelNumber": 277 },
  { "name": "Radio TV Neuquén (720p) [Not 24/7]", "embed": "hls-player.html?url=https://media.neuquen.gov.ar/rtn/television/playlist.m3u8", "category": "Argentina", "channelNumber": 278 },
  { "name": "Radio Yguazú TV (480p)", "embed": "hls-player.html?url=https://live.enhdtv.com:8081/radioiguazutv/index.m3u8", "category": "Argentina", "channelNumber": 279 },
  { "name": "Radiocanal San Francisco (1080p)", "embed": "hls-player.html?url=http://204.199.3.2/.m3u8", "category": "Argentina", "channelNumber": 280 },
  { "name": "RTN (Neuquén) (720p) [Not 24/7]", "embed": "hls-player.html?url=https://media.neuquen.gov.ar/rtn/television/media.m3u8", "category": "Argentina", "channelNumber": 281 },
  { "name": "San Pedro TV (1080p) [Not 24/7]", "embed": "hls-player.html?url=https://iptv.ixfo.com.ar:30443/live/sanpedrotv/playlist.m3u8", "category": "Argentina", "channelNumber": 282 },
  { "name": "Sicardi TV (720p)", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/sicarditv/sicarditv.m3u8", "category": "Argentina", "channelNumber": 283 },
  { "name": "Sony Channel (1080p)", "embed": "hls-player.html?url=http://38.183.182.166:8000/play/a0vg/index.m3u8", "category": "Argentina", "channelNumber": 284 },
  { "name": "TeleCinco Trelew (240p)", "embed": "hls-player.html?url=https://videohd.live:19360/8016/8016.m3u8", "category": "Argentina", "channelNumber": 285 },
  { "name": "Telefe (720p) [Geo-blocked]", "embed": "hls-player.html?url=https://telefe.com/Api/Videos/GetSourceUrl/694564/0/HLS?.m3u8", "category": "Argentina", "channelNumber": 286 },
  { "name": "Telefe (720p)", "embed": "hls-player.html?url=http://190.104.226.30/Live/870787012c00961adaf9b2304d704b57/telefe_720.m3u8", "category": "Argentina", "channelNumber": 287, "image": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Telefe_logo_%282018%29.svg" },
  { "name": "Telefe Rosario [Geo-blocked]", "embed": "hls-player.html?url=https://cdn-cirion01.sensa.com.ar/output/ARR2/TelefeRosarioH/playlist.m3u8", "category": "Argentina", "channelNumber": 288 },
  { "name": "Telemax", "embed": "hls-player.html?url=https://stream-gtlc.telecentro.net.ar/hls/telemaxhls/main.m3u8", "category": "Argentina", "channelNumber": 289 },
  { "name": "Telenord (720p) [Not 24/7]", "embed": "hls-player.html?url=https://617c5175c970b.streamlock.net:4444/previsoratv/live/playlist.m3u8", "category": "Argentina", "channelNumber": 290 },
  { "name": "Telenord Corrientes (1080p) [Not 24/7]", "embed": "hls-player.html?url=http://www.coninfo.net:1935/previsoratv/live/playlist.m3u8", "category": "Argentina", "channelNumber": 291 },
  { "name": "TN", "embed": "hls-player.html?url=http://190.104.226.30/Live/870787012c00961adaf9b2304d704b57/tn_720.m3u8", "category": "Argentina", "channelNumber": 292, "image": "https://upload.wikimedia.org/wikipedia/commons/5/53/Todo_Noticias_logo.svg" },
  { "name": "TV Maná Argentina (576p) [Not 24/7]", "embed": "hls-player.html?url=https://w2.manasat.com/tvmana-ar/smil:tvmana-ar.smil/playlist.m3u8", "category": "Argentina", "channelNumber": 293 },
  { "name": "TV Solidaria (576p)", "embed": "hls-player.html?url=https://canadaremar2.todostreaming.es/live/argentina-web.m3u8", "category": "Argentina", "channelNumber": 294 },
  { "name": "TV Universidad", "embed": "hls-player.html?url=https://stratus.stream.cespi.unlp.edu.ar/hls/tvunlp.m3u8", "category": "Argentina", "channelNumber": 295 },
  { "name": "TyC Sports (1080p) [Geo-blocked]", "embed": "hls-player.html?url=https://live-04-11-tyc24.vodgc.net/tyc24/index_tyc24_1080.m3u8", "category": "Argentina", "channelNumber": 296, "image": "https://upload.wikimedia.org/wikipedia/commons/2/22/TyC_Sports_Logo.svg" },
  { "name": "Unife TV", "embed": "hls-player.html?url=https://5dcabf026b188.streamlock.net/StreamUnife/livestream/playlist.m3u8", "category": "Argentina", "channelNumber": 297 },
  { "name": "Unife TV", "embed": "hls-player.html?url=https://cdn.mycloudstream.io/hls/live/broadcast/xundwjvp/index.m3u8", "category": "Argentina", "channelNumber": 298 },
  { "name": "Uniteve (720p) [Not 24/7]", "embed": "hls-player.html?url=https://vivo.solumedia.com:19360/uniteve/uniteve.m3u8", "category": "Argentina", "channelNumber": 299 },
  { "name": "Urban Mix (720p)", "embed": "hls-player.html?url=https://cloud.tvomix.com/URBANMIX/index.m3u8", "category": "Argentina", "channelNumber": 300 },
  { "name": "VerTV (VTV) (720p) [Not 24/7]", "embed": "hls-player.html?url=https://5f700d5b2c46f.streamlock.net/vertv/vertv/playlist.m3u8", "category": "Argentina", "channelNumber": 301 },
  { "name": "X Level Media (1080p)", "embed": "hls-player.html?url=https://tuvideoonline.com.ar:3332/live/xlevelmedialive.m3u8", "category": "Argentina", "channelNumber": 302 },
  { "name": "Xtrema Accion", "embed": "hls-player.html?url=https://stmv6.voxtvhd.com.br/cineaccion/cineaccion/playlist.m3u8", "category": "Argentina", "channelNumber": 303 },
  { "name": "Xtrema Cartoons", "embed": "hls-player.html?url=https://stmv6.voxtvhd.com.br/xtremacartoons/xtremacartoons/playlist.m3u8", "category": "Argentina", "channelNumber": 304 },
  { "name": "Xtrema Cine Clasico", "embed": "hls-player.html?url=https://stmv6.voxtvhd.com.br/cineclasico/cineclasico/playlist.m3u8", "category": "Argentina", "channelNumber": 305 },
  { "name": "Xtrema Terror", "embed": "hls-player.html?url=https://stmv6.voxtvhd.com.br/cineterror/cineterror/playlist.m3u8", "category": "Argentina", "channelNumber": 306 },
  { "name": "TV Publica (576p)", "embed": "hls-player.html?url=https://ola1.com.ar/tvp/index.m3u8", "category": "Argentina", "channelNumber": 307 }
];


export const CHANNEL_DESCRIPTIONS: Record<string, string> = {
  'Cartoon Network': 'Animated series and movies for kids featuring popular characters and original content.',
  'NICK': 'Nickelodeon - Kids entertainment with animated and live-action shows.',
  'Nicktoons': 'All cartoons, all the time! Classic and new animated series.',
  'Disney Channel': 'Family entertainment with original movies, series, and Disney favorites.',
  'Disney XD': 'Action-packed entertainment for kids with adventure shows and movies.',
  'Disney JR': 'Preschool programming and educational shows for young children.',
  'Nick JR': 'Educational programming for preschoolers.',
  'Sky Sports Premier League': 'Watch live Premier League football matches, highlights, analysis, and exclusive content.',
  'Fox Sports 1': 'Live sports coverage including NFL, MLB, college football, and more.',
  'Fox Sports 2': 'Additional sports programming and live events.',
  'ESPN USA': 'The worldwide leader in sports with live games, highlights, analysis, and sports news coverage.',
  'NHL': 'Official NHL channel featuring live hockey games, highlights, and behind-the-scenes content.',
  'NFL': 'Live NFL games, highlights, analysis, and football programming.',
  'NBA': 'Official NBA channel with live basketball games, highlights, and exclusive content.',
  'beIN Sports': 'International sports channel with soccer, tennis, motorsports, and more.',
  'Sky Sports Cricket': 'Live cricket matches, highlights, and cricket programming from around the world.',
  'WWE': 'Live WWE events, pay-per-views, original shows, and classic wrestling content.',
  'NBC USA': 'NBC network shows, news, sports, and entertainment.',
  'FX USA': 'Original dramas, comedies, and movies.',
  'Animal Planet': 'Wildlife documentaries, animal shows, and nature programming.',
  'Fox News': '24/7 news coverage and political analysis.',
  'CNN': 'Cable News Network with 24/7 news, analysis, and breaking stories.',
  'ABC USA': 'ABC network with news, entertainment, and family programming.',
  'MSNBC': 'News analysis, opinion, and live breaking news coverage.',
  'CNBC': 'Business news, market data, and financial programming.',
  'History USA': 'Historical documentaries, series, and educational programming.',
  'Univision': 'Spanish-language network with telenovelas, news, and entertainment.',
  'HGTV': 'Home and garden programming with renovation, design, and real estate shows.',
  'USA Network': 'Original series, movies, and entertainment programming.',
  'TLC': 'Reality shows and lifestyle programming featuring real-life stories.',
  'TBS': 'Comedy shows, movies, and sports programming.',
  'CBS': 'CBS network programming with news, entertainment, and sports.',
  'Telemundo': 'Spanish-language network with telenovelas, news, and entertainment.',
  'Boomerang': 'Classic cartoons and animated shows for kids.',
  'TN (Todo Noticias)': 'Canal de noticias de Argentina con información las 24 horas.',
  'Canal 26': 'Noticias nacionales e internacionales, deportes y actualidad desde Argentina.',
  'El Trece (CABA)': 'Canal abierto de Argentina con entretenimiento, noticias y ficción.',
  'TV Pública': 'Televisión Pública de Argentina con programación cultural y deportiva.',
  'C5N': 'Noticias y actualidad política de Argentina.',
  'LR+ (La Nación+)': 'Periodismo de investigación y análisis de la realidad argentina.',
  'Crónica TV': 'El canal de las placas rojas, noticias y música popular de Argentina.'
};


